### ISSUE TITLE
lio fails to build on ghc-8.8: LIO/TCB.hs:68:3: error:  ‘fail’ is not a (visible) method of class ‘Monad’

### ISSUE THREAD

**Issue by trofi** [PLSysSec/lio#55]
```
Configuring lio-0.11.7.0...
Preprocessing library for lio-0.11.7.0..
Building library for lio-0.11.7.0..
[ 1 of 23] Compiling LIO.TCB          ( LIO/TCB.hs, dist/build/LIO/TCB.o )

LIO/TCB.hs:68:3: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
   |
68 |   fail = LIOTCB . const . fail
   |   ^^^^
```

**Comment by deian** [comment]
Pushed to hackage too, thanks!
